@startuml
class ListManagement {
    +public ArrayList aList
    +public ArrayList names
    +public ArrayList complete
    +String sendName;
    +String sendInfo;

    +sendListToText()
    +sendCompleteToText()
    +sendNametoText()
    +recListFromText()
    +recNamesFromText()
    +recCompFromText()
}

class ListMoveOperations {


    +public String nameS;
    +public String descS;
    +public String dateS;



    +public String sendS;
    +public String recS;



    +public String remS;
    +public ArrayList aList
    +public ArrayList names
    +public ArrayList complete

        +incompListValue()
        +compListValue()
        +totalListValue()

        +newListValue()
        +newNameValue()
        +newDescValue()

        +sendValue()
        +recValue()

        +clearList()

        +editDescValue()
        +editDateValue()

        +compValue()
        +incompValue()
}

class ListController {
    +public TextField nameField;
    +public TextField descField;
    +public TextField dateField;

    +public String nameS;
    +public String descS;
    +public String dateS;

    +public TextField edescField;
    +public TextField edateField;
    +public String edescS;
    +public String edateS;

    +public TextField sendField;
    +public TextField recField;

    +public String sendS;
    +public String recS;

    +public TextField remField;

    +public String remS;



    +public String dispS;
    +public TextArea displayField;

    +public ArrayList aList
    +public ArrayList names
    +public ArrayList complete
    +public ListManagement lManage;


    +public TextField compField;
    +public String compS;
    +public TextField incompField;
    +public String incompS;

    +incompListValue()
    +compListValue()
    +totalListValue()

    +newListValue()
    +newNameValue()
    +newDescValue()

    +sendValue()
    +recValue()

    +clearList()

    +editDescValue()
    +editDateValue()

    +compValue()
    +incompValue()


}

class List {

    main()
    start()
}



javafx.Application <|-- List
List - ListController
ListController - ListManagement
ListController - ListMoveOperations
@enduml